# WhatATheme
markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: Nocom-Pila
# Description of the Site
description: Nocom-Pila web page
# URL of Image of the Site
site-image: https://github.com/vbarcena2020/Nocom-Pila/blob/master/assets/images/Nocom-pila.jpeg?raw=true
# Keywords of the Site
site-keywords: Site Nocom-Pila
# URL for the Image of custom Favicon
favicon-url: 

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: "https://github.com/vbarcena2020/Nocom-Pila/blob/master/assets/images/Nocom-pila.jpeg?raw=true"

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: nocompila.urjc@gmail.com
facebook_username: /
twitter_username: /
instagram_username: /
linkedin_username: /
github_username1:  vbarcena2020
github_username2:  mpancracio2020
github_username3:  javioled
github_username4:  mmunozs2020
youtube_channel_id: UCkxcA536jBns0uDtC1Zzx0A
reddit_username: /
behance_username: /
dribbble_username: /
spotify_username: /

# Google Analytics
google-analytics: UA-163806439-1

# Disqus
disqus-shortname: Nocom-Pila

# Name of the Author
author-name: Nocom-Pila
# URL for the Image of the Author
author-image: https://github.com/vbarcena2020/Nocom-Pila/blob/master/assets/images/NC_logo_img.png?raw=true
# 60 Words About the Author
author-about: We are a group composed by four software robotics engineering students, at King Juan Carlos University, Spain.
author-about1: This group was formed to carry out various robotic and software projects.  
author-about2: We have knowledge of various programming languages but the ones we have developed the most in are Python and C++. The midelware that we use to carry out our projects is ROS and ROS2 and the robots we have programed are Kobuki and Tiago.
author-about3: Finally, we are the winners of European RoboCup@Home Education 2022, Portugal.


# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://github.com/vbarcena2020

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
